/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import ptraitement.CentreTri;
import ptraitement.Dechet;
import ptraitement.Plateforme;
import ptraitement.Utilisateur;

/**
 *
 * @author camil
 */
public class FAccepterDemandeCollecte extends javax.swing.JDialog {

    private CentreTri centre;
    private Plateforme maPlat;

    /**
     * Creates new form FAccepterDemandeCollecte
     */
    public FAccepterDemandeCollecte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        maPlat = ((FAccueil) getParent()).getMaPlat();
        centre = (CentreTri) ((FAccueil) getParent()).getUti();
        ArrayList<String> liste = new ArrayList<>();
        for (int i = 0; i < maPlat.getListeDemandes().size(); i++) {
            if (maPlat.getListeDemandes().get(i).getCentre().equals(" ") && centre.getTypeDechetAccepte().contains(maPlat.getListeDemandes().get(i).getType())) {
                liste.add(maPlat.getListeDemandes().get(i).getID());
            }
        }
        Calendar calendar = Calendar.getInstance();
        Date ini = calendar.getTime();
        calendar.add(Calendar.DAY_OF_MONTH, -1);
        Date minDate = calendar.getTime();
        SpinnerDateModel model = new SpinnerDateModel(ini, minDate,null, Calendar.DAY_OF_MONTH);
        sDate.setModel(model);

// Format sans heure
        JSpinner.DateEditor editor = new JSpinner.DateEditor(sDate, "dd/MM/yyyy");
        sDate.setEditor(editor);

        cbDemandes.setModel(new DefaultComboBoxModel<>(liste.toArray(new String[0])));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bRetour = new javax.swing.JButton();
        cbDemandes = new javax.swing.JComboBox<>();
        bAccepter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sDate = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        bRetour.setText("Retour");
        bRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetourActionPerformed(evt);
            }
        });

        cbDemandes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDemandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDemandesActionPerformed(evt);
            }
        });

        bAccepter.setText("Accepter cette demande");
        bAccepter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAccepterActionPerformed(evt);
            }
        });

        jLabel1.setText("Date de la collecte");

        sDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1746286785786L), null, java.util.Calendar.DAY_OF_MONTH));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(cbDemandes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(bRetour))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAccepter)
                    .addComponent(sDate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(cbDemandes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(bAccepter)
                .addGap(7, 7, 7)
                .addComponent(bRetour)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void bRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetourActionPerformed
        this.setVisible(false);
        ((FAccueil) getParent()).getFichMCentre().setVisible(true);
    }//GEN-LAST:event_bRetourActionPerformed

    private void cbDemandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDemandesActionPerformed
        String nom = (String) cbDemandes.getSelectedItem();
        ArrayList<String> list = new ArrayList<>();
        for (int i = 0; i < maPlat.getListeDemandes().size(); i++) {
            if (maPlat.getListeDemandes().get(i).getID().equals(nom)) {
                String msg = ("identifiant du dechet : " + maPlat.getListeDemandes().get(i).getID()
                        + "\ntype du dechet : " + maPlat.getListeDemandes().get(i).getType()
                        + "\nquantite : " + maPlat.getListeDemandes().get(i).getQuantite()
                        + "\nclient : " + maPlat.getListeDemandes().get(i).getClient());
                JOptionPane.showMessageDialog(this, msg);
            }
        }
    }//GEN-LAST:event_cbDemandesActionPerformed

    private void bAccepterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAccepterActionPerformed
        Dechet demande = null;
        for (int i = 0; i < maPlat.getListeDemandes().size(); i++) {
            if (maPlat.getListeDemandes().get(i).getID().equals(cbDemandes.getSelectedItem().toString())) {
                demande = maPlat.getListeDemandes().get(i);
            }
        }
        Object Date = sDate.getValue();
        try {
            maPlat.fixerDateCollecte(centre, demande, Date);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Une erreur est survenue");
        }
        this.setVisible(false);
        ((FAccueil) getParent()).getFichMCentre().setVisible(true);
    }//GEN-LAST:event_bAccepterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAccepterDemandeCollecte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAccepterDemandeCollecte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAccepterDemandeCollecte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAccepterDemandeCollecte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FAccepterDemandeCollecte dialog = new FAccepterDemandeCollecte(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAccepter;
    private javax.swing.JButton bRetour;
    private javax.swing.JComboBox<String> cbDemandes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner sDate;
    // End of variables declaration//GEN-END:variables
}
