/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pfiches;

import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import ptraitement.Plateforme;
import ptraitement.Utilisateur;

/**
 *
 * @author camil
 */
public class FAccueil extends javax.swing.JFrame {

    private FInscription fichInsc;
    private FMenuPart fichMPart;
    private FConnexion fichCon;
    private FMenuEnt fichMEnt;
    private FMenuCentre fichMCentre;
    //ajouter attributs pour autres fiches
    private Plateforme maPlat;
    private Utilisateur uti;
    private ArrayList<String> DechetsPossibles;

    /**
     * Creates new form FAccueil
     */
    public FAccueil() {
        initComponents();
        DechetsPossibles = new ArrayList<>();
        DechetsPossibles.add("Electromenager");
        DechetsPossibles.add("Informatique");
        DechetsPossibles.add("Telecommunication");
        DechetsPossibles.add("Jouets");
        DechetsPossibles.add("Cameras");
        fichInsc = new FInscription(this, false);
        fichMPart = new FMenuPart(this, false);
        fichCon = new FConnexion(this, false);
        fichMEnt = new FMenuEnt(this, false);
        fichMCentre = new FMenuCentre(this, false);
        //rajouter ici les autres fiches
        maPlat = new Plateforme();
        try {
            maPlat.chargerClients();
            maPlat.chargerCentres();
            maPlat.chargerDemandes();
            maPlat.chargerDechets();
            maPlat.MAJ();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Les données n'ont pas pu être chargées");
        }
    }

    //gettas (accessors)
    public FInscription getFichInsc() {
        return fichInsc;
    }
    
    public FConnexion getFichCon(){
        return fichCon;
    }

    public Plateforme getMaPlat() {
        return maPlat;
    }

    public FMenuPart getFichMPart() {
        return fichMPart;
    }

    public FMenuEnt getFichMEnt() {
        return fichMEnt;
    }

    public FMenuCentre getFichMCentre() {
        return fichMCentre;
    }

    public void setUti(Utilisateur uti) {
        this.uti = uti;
    }

    public Utilisateur getUti() {
        return uti;
    }

    public ArrayList<String> getDechetsPos() {
        return DechetsPossibles;
    }

    public void setDechetsPos(ArrayList<String> DechetsPos) {
        DechetsPossibles = DechetsPos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bInscription = new javax.swing.JButton();
        bConnexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil");

        bInscription.setText("Inscription");
        bInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInscriptionActionPerformed(evt);
            }
        });

        bConnexion.setText("Connexion");
        bConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConnexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(bConnexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(bInscription)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bInscription)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bConnexion)
                        .addGap(87, 87, 87))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInscriptionActionPerformed
        this.setVisible(false);
        fichInsc.setVisible(true);
    }//GEN-LAST:event_bInscriptionActionPerformed

    private void bConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConnexionActionPerformed
        this.setVisible(false);
        fichCon.setVisible(true);
    }//GEN-LAST:event_bConnexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConnexion;
    private javax.swing.JButton bInscription;
    // End of variables declaration//GEN-END:variables
}
