/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;

import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import ptraitement.CentreTri;
import ptraitement.Entreprise;
import ptraitement.Particulier;
import ptraitement.Utilisateur;

/**
 *
 * @author camil
 */
public class FHisto extends javax.swing.JDialog {

    Utilisateur uti;

    /**
     * Creates new form FHisto
     */
    public FHisto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        uti = ((FAccueil) getParent()).getUti();
        if (uti instanceof Entreprise) {
            rbDate.setText("Date de collecte");
        } else if (uti instanceof Particulier) {
            rbDate.setText("Date de dépot");
        } else if (uti instanceof CentreTri) {
            rbDate.setText("Date de collecte ou de dépot");
            rbCentreClient.setText("Client");
        }
        JTableHeader header = tTri.getTableHeader();
        TableColumnModel columnModel = tTri.getColumnModel();
        columnModel.getColumn(0).setHeaderValue(rbDate.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        rbDate = new javax.swing.JRadioButton();
        rbType = new javax.swing.JRadioButton();
        rbCentreClient = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tTri = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Trier par :");

        buttonGroup.add(rbDate);
        rbDate.setSelected(true);
        rbDate.setText("jRadioButton1");
        rbDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDateActionPerformed(evt);
            }
        });

        buttonGroup.add(rbType);
        rbType.setText("Type de déchets");
        rbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTypeActionPerformed(evt);
            }
        });

        buttonGroup.add(rbCentreClient);
        rbCentreClient.setText("Centre de recyclage");
        rbCentreClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCentreClientActionPerformed(evt);
            }
        });

        tTri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Nom du déchet", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tTri);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbDate)
                        .addGap(18, 18, 18)
                        .addComponent(rbType)
                        .addGap(18, 18, 18)
                        .addComponent(rbCentreClient))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDate)
                    .addComponent(rbType)
                    .addComponent(rbCentreClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void rbDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDateActionPerformed
        JTableHeader header = tTri.getTableHeader();
        TableColumnModel columnModel = tTri.getColumnModel();
        // Change le titre de la 1ère colonne (index 0)
        columnModel.getColumn(0).setHeaderValue(rbDate.getText());
        // Rafraîchir l'affichage de l'en-tête
        header.repaint();
    }//GEN-LAST:event_rbDateActionPerformed

    private void rbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTypeActionPerformed
        JTableHeader header = tTri.getTableHeader();
        TableColumnModel columnModel = tTri.getColumnModel();
        // Change le titre de la 1ère colonne (index 0)
        columnModel.getColumn(0).setHeaderValue(rbType.getText());
        // Rafraîchir l'affichage de l'en-tête
        header.repaint();
    }//GEN-LAST:event_rbTypeActionPerformed

    private void rbCentreClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCentreClientActionPerformed
        JTableHeader header = tTri.getTableHeader();
        TableColumnModel columnModel = tTri.getColumnModel();
        // Change le titre de la 1ère colonne (index 0)
        columnModel.getColumn(0).setHeaderValue(rbCentreClient.getText());
        // Rafraîchir l'affichage de l'en-tête
        header.repaint();
    }//GEN-LAST:event_rbCentreClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FHisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FHisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FHisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FHisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FHisto dialog = new FHisto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbCentreClient;
    private javax.swing.JRadioButton rbDate;
    private javax.swing.JRadioButton rbType;
    private javax.swing.JTable tTri;
    // End of variables declaration//GEN-END:variables
}
