/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;

import java.io.IOException;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import ptraitement.Plateforme;
import ptraitement.Utilisateur;

/**
 *
 * @author camil
 */
public class FInscription extends javax.swing.JDialog {

    private ArrayList<String> DechetsPossibles;
    private Utilisateur uti;

    /**
     * Creates new form FInscription
     */
    public FInscription(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        PCentre.setVisible(false);
        DechetsPossibles = ((FAccueil) getParent()).getDechetsPos();
        DefaultListModel<String> model = new DefaultListModel<>();
        for (String dechet : DechetsPossibles) {
            model.addElement(dechet);
        }
        liDechets.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bRetour = new javax.swing.JButton();
        lEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfMdp = new javax.swing.JTextField();
        lMdp = new javax.swing.JLabel();
        bValider = new javax.swing.JButton();
        cbUti = new javax.swing.JComboBox<>();
        lUti = new javax.swing.JLabel();
        tfNom = new javax.swing.JTextField();
        tfPrenom = new javax.swing.JTextField();
        tfTel = new javax.swing.JTextField();
        tfAdresse = new javax.swing.JTextField();
        lNom = new javax.swing.JLabel();
        lPrenom = new javax.swing.JLabel();
        lTel = new javax.swing.JLabel();
        lAdresse = new javax.swing.JLabel();
        PCentre = new javax.swing.JPanel();
        lDechets = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liDechets = new javax.swing.JList<>();
        bAjouter = new javax.swing.JButton();
        cbOuverture = new javax.swing.JComboBox<>();
        lOuverture = new javax.swing.JLabel();
        lFermeture = new javax.swing.JLabel();
        cbFermeture = new javax.swing.JComboBox<>();
        lCapacite = new javax.swing.JLabel();
        sCapacite = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inscription");
        setFocusTraversalPolicyProvider(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        bRetour.setText("Retour");
        bRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetourActionPerformed(evt);
            }
        });

        lEmail.setText("Email");

        lMdp.setText("Mot de passe");

        bValider.setText("Valider");
        bValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValiderActionPerformed(evt);
            }
        });

        cbUti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particulier", "Entreprise", "Centre de Tri" }));
        cbUti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUtiActionPerformed(evt);
            }
        });

        lUti.setText("Type d'utilisateur");

        lNom.setText("Nom");

        lPrenom.setText("Prenom");

        lTel.setText("Telephone");

        lAdresse.setText("Adresse");

        lDechets.setText("Type de dechets acceptés");

        liDechets.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(liDechets);

        bAjouter.setText("Ajouter un type de déchets");

        cbOuverture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00" }));

        lOuverture.setText("Heure d'ouverture");

        lFermeture.setText("Heure de fermeture");

        cbFermeture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30" }));

        lCapacite.setText("Capacite de stockage (en tonnes)");

        sCapacite.setModel(new javax.swing.SpinnerNumberModel(1.0f, 1.0f, null, 0.5f));
        sCapacite.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout PCentreLayout = new javax.swing.GroupLayout(PCentre);
        PCentre.setLayout(PCentreLayout);
        PCentreLayout.setHorizontalGroup(
            PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCentreLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lOuverture)
                    .addComponent(lFermeture)
                    .addComponent(lCapacite)
                    .addComponent(lDechets)
                    .addComponent(bAjouter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(PCentreLayout.createSequentialGroup()
                        .addGroup(PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbOuverture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbFermeture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sCapacite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PCentreLayout.setVerticalGroup(
            PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCentreLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PCentreLayout.createSequentialGroup()
                        .addComponent(lDechets)
                        .addGap(18, 18, 18)
                        .addComponent(bAjouter))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOuverture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lOuverture))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFermeture)
                    .addComponent(cbFermeture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCapacite)
                    .addComponent(sCapacite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTel)
                    .addComponent(lUti)
                    .addComponent(lMdp)
                    .addComponent(lNom)
                    .addComponent(lPrenom)
                    .addComponent(lEmail)
                    .addComponent(lAdresse)
                    .addComponent(bRetour))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(bValider)
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbUti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMdp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPrenom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAdresse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(PCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(13, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfAdresse, tfEmail, tfMdp, tfNom, tfPrenom, tfTel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbUti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lUti))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lEmail)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lMdp)
                            .addComponent(tfMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lPrenom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lTel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lAdresse)
                            .addComponent(tfAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(PCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRetour)
                    .addComponent(bValider))
                .addGap(34, 34, 34))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfAdresse, tfEmail, tfMdp, tfNom, tfPrenom, tfTel});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetourActionPerformed
        this.setVisible(false);
        this.getParent().setVisible(true);
    }//GEN-LAST:event_bRetourActionPerformed

    private void bValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValiderActionPerformed
        Plateforme maPlat = ((FAccueil) getParent()).getMaPlat();
        String email = tfEmail.getText();
        String mdp = tfMdp.getText();
        String nom = tfNom.getText();
        String prenom = tfPrenom.getText();
        String tel = tfTel.getText();
        String adresse = tfAdresse.getText();
        LocalTime ouv = LocalTime.parse((CharSequence) cbOuverture.getSelectedItem());
        LocalTime ferm = LocalTime.parse((CharSequence) cbFermeture.getSelectedItem());
        ArrayList<String> typeD = new ArrayList<>(liDechets.getSelectedValuesList());
        float capacite = ((Number) sCapacite.getValue()).floatValue();
        if (email.isEmpty() || mdp.isEmpty() || nom.isEmpty() || tel.isEmpty() || adresse.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuilliez remplir tout les champs avant de valider");
        } else {
            try {
                switch (cbUti.getSelectedIndex()) {
                    case 0:
                        if (prenom.isEmpty()) {
                            JOptionPane.showMessageDialog(this, "Veuilliez remplir tout les champs avant de valider");
                        } else {
                            uti = maPlat.inscriptionPart(email, mdp, nom, prenom, tel, adresse);
                            ((FAccueil) getParent()).setUti(uti);
                            maPlat.sauvegarderClients();
                            this.setVisible(false);
                            ((FAccueil) getParent()).getFichMPart().setVisible(true);
                            break;
                        }
                    case 1:
                        uti = maPlat.inscriptionEnt(email, mdp, nom, tel, adresse);
                        ((FAccueil) getParent()).setUti(uti);
                        maPlat.sauvegarderClients();
                        this.setVisible(false);
                        ((FAccueil) getParent()).getFichMEnt().setVisible(true);
                        break;
                    case 2:
                        if (liDechets.isSelectionEmpty()) {
                            JOptionPane.showMessageDialog(this, "Veuilliez remplir tout les champs avant de valider");
                        } else {
                            uti = maPlat.inscriptionCentre(email, mdp, nom, tel, adresse, typeD, ouv, ferm, capacite);
                            ((FAccueil) getParent()).setUti(uti);
                            maPlat.sauvegarderCentres();
                            break;
                        }
                    default:
                        break;
                }
            } catch (IOException ex) {
                //message d'erreur
            }
        }


    }//GEN-LAST:event_bValiderActionPerformed

    private void cbUtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUtiActionPerformed
        if (cbUti.getSelectedIndex() == 0) {
            tfPrenom.setEnabled(true);
            PCentre.setVisible(false);
        }
        if (cbUti.getSelectedIndex() == 1) {
            tfPrenom.setEnabled(false);
            PCentre.setVisible(false);
        }
        if (cbUti.getSelectedIndex() == 2) {
            tfPrenom.setEnabled(false);
            PCentre.setVisible(true);
        }

    }//GEN-LAST:event_cbUtiActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FInscription dialog = new FInscription(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PCentre;
    private javax.swing.JButton bAjouter;
    private javax.swing.JButton bRetour;
    private javax.swing.JButton bValider;
    private javax.swing.JComboBox<String> cbFermeture;
    private javax.swing.JComboBox<String> cbOuverture;
    private javax.swing.JComboBox<String> cbUti;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAdresse;
    private javax.swing.JLabel lCapacite;
    private javax.swing.JLabel lDechets;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lFermeture;
    private javax.swing.JLabel lMdp;
    private javax.swing.JLabel lNom;
    private javax.swing.JLabel lOuverture;
    private javax.swing.JLabel lPrenom;
    private javax.swing.JLabel lTel;
    private javax.swing.JLabel lUti;
    private javax.swing.JList<String> liDechets;
    private javax.swing.JSpinner sCapacite;
    private javax.swing.JTextField tfAdresse;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfMdp;
    private javax.swing.JTextField tfNom;
    private javax.swing.JTextField tfPrenom;
    private javax.swing.JTextField tfTel;
    // End of variables declaration//GEN-END:variables
}
