/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import ptraitement.CentreTri;
import ptraitement.Entreprise;
import ptraitement.Plateforme;
import ptraitement.Utilisateur;

/**
 *
 * @author camil
 */
public class FMenuCentre extends javax.swing.JDialog {

    private FModifierInfos fichMInf;
    private Utilisateur uti;
    private CentreTri centre;

    /**
     * Creates new form FMenuCentre
     */
    public FMenuCentre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        uti = ((FAccueil) getParent()).getUti();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bVoirDCollectes = new javax.swing.JButton();
        bVoirCollectes = new javax.swing.JButton();
        bHisto = new javax.swing.JButton();
        bInfos = new javax.swing.JButton();
        bDeco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel2.setText("Bienvenu dans votre espace client !");

        jLabel1.setText("Voulez-vous:");

        bVoirDCollectes.setText("Consulter la liste des demandes de collecte");
        bVoirDCollectes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoirDCollectesActionPerformed(evt);
            }
        });

        bVoirCollectes.setText("Consulter la liste des collectes que vous devez effectuer");
        bVoirCollectes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoirCollectesActionPerformed(evt);
            }
        });

        bHisto.setText("Consulter votre historique de dechets recyclés");
        bHisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHistoActionPerformed(evt);
            }
        });

        bInfos.setText("Modifier les informations de votre compte");
        bInfos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInfosActionPerformed(evt);
            }
        });

        bDeco.setText("Déconnexion");
        bDeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(bDeco))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(bVoirDCollectes)
                            .addComponent(bVoirCollectes)
                            .addComponent(bHisto)
                            .addComponent(bInfos)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bVoirDCollectes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bVoirCollectes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bHisto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bInfos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(bDeco)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bHistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHistoActionPerformed
        uti = ((FAccueil) getParent()).getUti();
        JOptionPane.showMessageDialog(this, uti.getHisto());
    }//GEN-LAST:event_bHistoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void bVoirDCollectesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoirDCollectesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bVoirDCollectesActionPerformed

    private void bInfosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInfosActionPerformed
        fichMInf = new FModifierInfos(((FAccueil) getParent()), false);
        this.setVisible(false);
        fichMInf.setVisible(true);
    }//GEN-LAST:event_bInfosActionPerformed

    private void bDecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDecoActionPerformed
        ((FAccueil) getParent()).setUti(null);
        this.setVisible(false);
        this.getParent().setVisible(true);
    }//GEN-LAST:event_bDecoActionPerformed

    private void bVoirCollectesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoirCollectesActionPerformed
        uti = ((FAccueil) getParent()).getUti();
        if (uti instanceof CentreTri) {
            centre = (CentreTri) uti;
        }
        Plateforme maPlat = ((FAccueil) getParent()).getMaPlat();
        ArrayList<String> liste = new ArrayList();
        for (int i = 0; i < maPlat.getListeDemandes().size(); i++) {
            if (maPlat.getListeDemandes().get(i).getCentre().equals(centre.getMail())) {
                liste.add(maPlat.getListeDemandes().get(i).toString());
            }
        }
        JOptionPane.showMessageDialog(this, String.join("\n\n", liste));
    }//GEN-LAST:event_bVoirCollectesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenuCentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenuCentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenuCentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenuCentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FMenuCentre dialog = new FMenuCentre(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDeco;
    private javax.swing.JButton bHisto;
    private javax.swing.JButton bInfos;
    private javax.swing.JButton bVoirCollectes;
    private javax.swing.JButton bVoirDCollectes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
