/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;

import java.io.IOException;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ptraitement.CentreTri;
import ptraitement.Entreprise;
import ptraitement.Particulier;
import ptraitement.Plateforme;
import ptraitement.Utilisateur;

/**
 *
 * @author camil
 */
public class FModifierInfos extends javax.swing.JDialog {

    ArrayList<String> DechetsPossibles;
    Utilisateur uti;

    /**
     * Creates new form FModifierInfos
     */
    public FModifierInfos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        DechetsPossibles = new ArrayList<>();
        uti = ((FAccueil) getParent()).getUti();
        tfEmail.setText(uti.getMail());
        tfMdp.setText(uti.getMdp());
        tfNom.setText(uti.getNom());
        tfTel.setText(uti.getTel());
        tfAdresse.setText(uti.getAdresse());
        if (uti instanceof Entreprise) {
            PCentre.setVisible(false);
            tfPrenom.setEnabled(false);
        } else if (uti instanceof CentreTri centre) {
            tfPrenom.setEnabled(false);
            //liDechets.setSelectedIndices(indices);

        } else if (uti instanceof Particulier particulier) {
            PCentre.setVisible(false);
            tfPrenom.setText(particulier.getPrenom());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bRetour = new javax.swing.JButton();
        lEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfMdp = new javax.swing.JTextField();
        lMdp = new javax.swing.JLabel();
        bValider = new javax.swing.JButton();
        tfNom = new javax.swing.JTextField();
        tfPrenom = new javax.swing.JTextField();
        tfTel = new javax.swing.JTextField();
        tfAdresse = new javax.swing.JTextField();
        lNom = new javax.swing.JLabel();
        lPrenom = new javax.swing.JLabel();
        lTel = new javax.swing.JLabel();
        lAdresse = new javax.swing.JLabel();
        PCentre = new javax.swing.JPanel();
        lDechets = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liDechets = new javax.swing.JList<>();
        bAjouter = new javax.swing.JButton();
        cbOuverture = new javax.swing.JComboBox<>();
        lOuverture = new javax.swing.JLabel();
        lFermeture = new javax.swing.JLabel();
        cbFermeture = new javax.swing.JComboBox<>();
        lCapacite = new javax.swing.JLabel();
        sCapacite = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modifier Infos");
        setFocusTraversalPolicyProvider(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        bRetour.setText("Retour");
        bRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetourActionPerformed(evt);
            }
        });

        lEmail.setText("email");

        lMdp.setText("mot de passe");

        bValider.setText("Valider");
        bValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValiderActionPerformed(evt);
            }
        });

        lNom.setText("Nom");

        lPrenom.setText("Prenom");

        lTel.setText("Telephone");

        lAdresse.setText("Adresse");

        lDechets.setText("Type de dechets acceptés");

        liDechets.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(liDechets);

        bAjouter.setText("Ajouter un type de déchets");

        cbOuverture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00" }));

        lOuverture.setText("Heure d'ouverture");

        lFermeture.setText("Heure de fermeture");

        cbFermeture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30" }));

        lCapacite.setText("Capacite de stockage (en tonnes)");

        sCapacite.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sCapacite.setDoubleBuffered(true);

        javax.swing.GroupLayout PCentreLayout = new javax.swing.GroupLayout(PCentre);
        PCentre.setLayout(PCentreLayout);
        PCentreLayout.setHorizontalGroup(
            PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCentreLayout.createSequentialGroup()
                .addGroup(PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PCentreLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lDechets)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PCentreLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lOuverture)
                            .addComponent(bAjouter)
                            .addComponent(lFermeture)
                            .addComponent(lCapacite))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(PCentreLayout.createSequentialGroup()
                        .addGroup(PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sCapacite, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbOuverture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbFermeture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 89, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PCentreLayout.setVerticalGroup(
            PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCentreLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PCentreLayout.createSequentialGroup()
                        .addComponent(lDechets)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bAjouter)))
                .addGap(18, 18, 18)
                .addGroup(PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOuverture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lOuverture))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFermeture)
                    .addComponent(cbFermeture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCapacite)
                    .addComponent(sCapacite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lEmail)
                    .addComponent(lMdp)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lPrenom)
                            .addComponent(lNom)
                            .addComponent(lTel)
                            .addComponent(lAdresse)
                            .addComponent(bRetour))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addComponent(PCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(bValider)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lEmail)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lMdp)
                            .addComponent(tfMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lPrenom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lTel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lAdresse)))
                    .addComponent(PCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bValider)
                    .addComponent(bRetour))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetourActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.getParent().setVisible(true);
    }//GEN-LAST:event_bRetourActionPerformed

    private void bValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValiderActionPerformed
        // TODO add your handling code here:
        Plateforme maPlat = ((FAccueil) getParent()).getMaPlat();
        String email = tfEmail.getText();
        String mdp = tfMdp.getText();
        String nom = tfNom.getText();
        String prenom = tfPrenom.getText();
        String tel = tfTel.getText();
        String adresse = tfAdresse.getText();
        LocalTime ouv = LocalTime.parse((CharSequence) cbOuverture.getSelectedItem());
        LocalTime ferm = LocalTime.parse((CharSequence) cbFermeture.getSelectedItem());
        ArrayList<String> typeD = new ArrayList<>(liDechets.getSelectedValuesList());
        float capacite = ((Number) sCapacite.getValue()).floatValue();
        if (email.isEmpty() || mdp.isEmpty() || nom.isEmpty() || tel.isEmpty() || adresse.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuilliez remplir tout les champs avant de valider");
        } else {
            try {
                if (uti instanceof Particulier) {
                    if (prenom.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Veuilliez remplir tout les champs avant de valider");
                    } else {
                        ((FAccueil) getParent()).setUti(uti);
                        maPlat.sauvegarderClients();
                        this.setVisible(false);
                        ((FAccueil) getParent()).getFichMPart().setVisible(true);
                    }
                } else if (uti instanceof Entreprise) {
                    ((FAccueil) getParent()).setUti(uti);
                    maPlat.sauvegarderClients();
                } else if (uti instanceof CentreTri) {
                    if (liDechets.isSelectionEmpty()) {
                        JOptionPane.showMessageDialog(this, "Veuilliez remplir tout les champs avant de valider");
                    } else {
                        ((FAccueil) getParent()).setUti(uti);
                        maPlat.sauvegarderCentres();

                    }
                }
            } catch (IOException ex) {
                //message d'erreur
            }
        }


    }//GEN-LAST:event_bValiderActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FModifierInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FModifierInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FModifierInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FModifierInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FModifierInfos dialog = new FModifierInfos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PCentre;
    private javax.swing.JButton bAjouter;
    private javax.swing.JButton bRetour;
    private javax.swing.JButton bValider;
    private javax.swing.JComboBox<String> cbFermeture;
    private javax.swing.JComboBox<String> cbOuverture;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAdresse;
    private javax.swing.JLabel lCapacite;
    private javax.swing.JLabel lDechets;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lFermeture;
    private javax.swing.JLabel lMdp;
    private javax.swing.JLabel lNom;
    private javax.swing.JLabel lOuverture;
    private javax.swing.JLabel lPrenom;
    private javax.swing.JLabel lTel;
    private javax.swing.JList<String> liDechets;
    private javax.swing.JSpinner sCapacite;
    private javax.swing.JTextField tfAdresse;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfMdp;
    private javax.swing.JTextField tfNom;
    private javax.swing.JTextField tfPrenom;
    private javax.swing.JTextField tfTel;
    // End of variables declaration//GEN-END:variables
}
