/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import ptraitement.CentreTri;
import ptraitement.Plateforme;

/**
 *
 * @author camil
 */
public class FRechercheCentre extends javax.swing.JDialog {

    private Plateforme maPlat;
    private ArrayList<String> DechetsPossibles;

    /**
     * Creates new form FRechercheCentre
     */
    public FRechercheCentre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cbDechets.setVisible(false);
        cbCentres2.setVisible(false);
        maPlat = ((FAccueil) getParent()).getMaPlat();
        DechetsPossibles = ((FAccueil) getParent()).getDechetsPos();
        cbDechets.setModel(new DefaultComboBoxModel<>(DechetsPossibles.toArray(new String[0])));
        ArrayList<String> centres = new ArrayList<>();
        for (int i = 0; i < maPlat.getListeCentres().size(); i++) {
            centres.add(maPlat.getListeCentres().get(i).getNom());
        }
        cbCentres.setModel(new DefaultComboBoxModel<>(centres.toArray(new String[0])));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbAfficher = new javax.swing.JRadioButton();
        rbRechercher = new javax.swing.JRadioButton();
        cbCentres = new javax.swing.JComboBox<>();
        cbDechets = new javax.swing.JComboBox<>();
        cbCentres2 = new javax.swing.JComboBox<>();
        bRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Voulez-vous :");

        buttonGroup.add(rbAfficher);
        rbAfficher.setSelected(true);
        rbAfficher.setText("Afficher la liste des centres");
        rbAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAfficherActionPerformed(evt);
            }
        });

        buttonGroup.add(rbRechercher);
        rbRechercher.setText("Recherche a partir des déchets acceptés");
        rbRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRechercherActionPerformed(evt);
            }
        });

        cbCentres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCentres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCentresActionPerformed(evt);
            }
        });

        cbDechets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDechets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDechetsActionPerformed(evt);
            }
        });

        cbCentres2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCentres2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCentres2ActionPerformed(evt);
            }
        });

        bRetour.setText("Retour");
        bRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAfficher)
                    .addComponent(cbCentres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCentres2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbRechercher)
                    .addComponent(cbDechets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(bRetour)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAfficher)
                    .addComponent(rbRechercher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCentres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDechets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbCentres2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(bRetour)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void rbAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAfficherActionPerformed
        cbCentres.setVisible(true);
        cbDechets.setVisible(false);
        cbCentres2.setVisible(false);
    }//GEN-LAST:event_rbAfficherActionPerformed

    private void cbCentresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCentresActionPerformed
        String ncentre = (String) cbCentres.getSelectedItem();
        CentreTri centre = null;
        for (int i = 0; i < maPlat.getListeCentres().size(); i++) {
            if (ncentre.equals(maPlat.getListeCentres().get(i).getNom())) {
                centre = maPlat.getListeCentres().get(i);
            }
        }
        JOptionPane.showMessageDialog(this, "Heure d'ouverture : " + centre.getOuverture() + "\nHeure de fermeture : "
                + centre.getFermeture() + "\nType de dechets acceptes : " + centre.getTypeDechetAccepte());
    }//GEN-LAST:event_cbCentresActionPerformed

    private void rbRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRechercherActionPerformed
        cbDechets.setVisible(true);
        cbCentres.setVisible(false);
    }//GEN-LAST:event_rbRechercherActionPerformed

    private void cbDechetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDechetsActionPerformed
        String type = (String) cbDechets.getSelectedItem();
        ArrayList<String> ncentres = new ArrayList<>();
        for (int i = 0; i < maPlat.getListeCentres().size(); i++) {
            if (maPlat.getListeCentres().get(i).getTypeDechetAccepte().contains(type)) {
                ncentres.add(maPlat.getListeCentres().get(i).getNom());
            }
        }
        cbCentres2.setVisible(true);
        cbCentres2.setModel(new DefaultComboBoxModel<>(ncentres.toArray(new String[0])));
    }//GEN-LAST:event_cbDechetsActionPerformed

    private void cbCentres2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCentres2ActionPerformed
        String ncentre = (String) cbCentres.getSelectedItem();
        CentreTri centre = null;
        for (int i = 0; i < maPlat.getListeCentres().size(); i++) {
            if (ncentre.equals(maPlat.getListeCentres().get(i).getNom())) {
                centre = maPlat.getListeCentres().get(i);
            }
        }
        JOptionPane.showMessageDialog(this, "Heure d'ouverture : " + centre.getOuverture() + "\nHeure de fermeture : "
                + centre.getFermeture() + "\nType de dechets acceptes : " + centre.getTypeDechetAccepte());
    }//GEN-LAST:event_cbCentres2ActionPerformed

    private void bRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetourActionPerformed
        this.setVisible(false);
        ((FAccueil) getParent()).getFichMPart().setVisible(true);
    }//GEN-LAST:event_bRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRechercheCentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRechercheCentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRechercheCentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRechercheCentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRechercheCentre dialog = new FRechercheCentre(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRetour;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox<String> cbCentres;
    private javax.swing.JComboBox<String> cbCentres2;
    private javax.swing.JComboBox<String> cbDechets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbAfficher;
    private javax.swing.JRadioButton rbRechercher;
    // End of variables declaration//GEN-END:variables
}
